import type { SavedReportItem } from '../types';

interface GeneratedReportsHistoryProps {
  history: SavedReportItem[];
  loading: boolean;
  onExportCsv: (reportType: string) => Promise<void>;
}

export function GeneratedReportsHistory({
  history,
  loading,
  onExportCsv,
}: GeneratedReportsHistoryProps) {
  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center rounded-2xl border border-gray-200 bg-white">
        <div className="flex flex-col items-center gap-2">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent" />
          <p className="text-xs font-medium text-gray-500">Loading archived reports history...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-xs">
      <div className="border-b border-gray-200 px-5 py-4 sm:flex sm:items-center sm:justify-between">
        <div>
          <h2 className="text-base font-bold text-gray-900">Generated Reports Archive & History</h2>
          <p className="text-xs text-gray-500">
            Audit history of generated executive snapshots and exported files (SRS Section 4.4.4)
          </p>
        </div>
        <div className="mt-2 text-xs font-medium text-gray-500 sm:mt-0">
          <span className="font-bold text-gray-900">{history.length}</span> archived reports
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs sm:text-sm">
          <thead className="border-b border-gray-200 bg-gray-50/80 text-[11px] font-bold uppercase tracking-wider text-gray-500">
            <tr>
              <th className="px-5 py-3.5">Report Title</th>
              <th className="px-4 py-3.5">Module Type</th>
              <th className="px-4 py-3.5">Generated By</th>
              <th className="px-4 py-3.5">Parameters</th>
              <th className="px-4 py-3.5 text-right">Archived Date</th>
              <th className="px-5 py-3.5 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100 text-gray-700">
            {history.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-5 py-12 text-center text-gray-400">
                  No generated report records found.
                </td>
              </tr>
            ) : (
              history.map((rep) => (
                <tr key={rep.id} className="hover:bg-gray-50/60 transition-colors">
                  <td className="px-5 py-3.5">
                    <div className="font-bold text-gray-900">{rep.name}</div>
                    <div className="font-mono text-[11px] text-gray-400">ID: {rep.id}</div>
                  </td>
                  <td className="px-4 py-3.5">
                    <span className="inline-flex rounded-md bg-blue-50 px-2 py-0.5 text-xs font-bold text-blue-700 uppercase">
                      {rep.type}
                    </span>
                  </td>
                  <td className="px-4 py-3.5 text-gray-700">
                    {rep.generatorName || 'System User'}
                  </td>
                  <td className="px-4 py-3.5 font-mono text-[11px] text-gray-500 max-w-xs truncate">
                    {JSON.stringify(rep.parameters)}
                  </td>
                  <td className="px-4 py-3.5 text-right text-xs text-gray-500 whitespace-nowrap">
                    {new Date(rep.createdAt).toLocaleString()}
                  </td>
                  <td className="px-5 py-3.5 text-right whitespace-nowrap">
                    <button
                      type="button"
                      onClick={() => onExportCsv(rep.type)}
                      className="inline-flex cursor-pointer items-center gap-1 rounded-lg border border-gray-200 bg-white px-2.5 py-1 text-xs font-semibold text-blue-600 hover:bg-blue-50 transition-colors shadow-2xs"
                    >
                      <svg
                        className="h-3.5 w-3.5"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        strokeWidth="2"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
                        />
                      </svg>
                      Re-export
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
